FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY lab3/api ./lab3/api
COPY lab3/worker ./lab3/worker

EXPOSE 8000

CMD ["uvicorn", "lab3.api.main:app", "--host", "0.0.0.0", "--port", "8000"]