services:

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: a1111
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workout_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./lab3/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U a1111 -d workout_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://a1111:postgres@db:5432/workout_db
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      parser:
        condition: service_started
      redis:
        condition: service_started

  parser:
    build:
      context: .
      dockerfile: Dockerfile.parser
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://a1111:postgres@db:5432/workout_db
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: celery -A lab3.worker.main.celery_app worker --loglevel=info
    environment:
      DATABASE_URL: postgresql://a1111:postgres@db:5432/workout_db
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      parser:
        condition: service_started

volumes:
  postgres_data: