"""add level to exercise muscle group

Revision ID: c19fad4a2717
Revises: 0f53545aed78
Create Date: 2026-09-29 20:54:09.298210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c19fad4a2717'
down_revision: Union[str, Sequence[str], None] = '0f53545aed78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercisemusclegrouplink', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercisemusclegrouplink', 'level')
    # ### end Alembic commands ###
